version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: simpleblog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog12345
    ports:
      - "5432:5432"
    volumes:
      - pg_data2:/var/lib/postgresql/data

volumes:
  pg_data2:
